### ISSUE TITLE
Checkbox are not intuitive

### ISSUE THREAD

**Issue by frenetic** [vintasoftware/django-apps-checklist#7]
The first time I visited the project, I thought the checkbox were CSS bullets for list items. Since the entire page is "Django Green", my mind assimilated those white boxes as bullets.

Today I visited the site again and realized those were checkboxes - and the entire site made much more sense to me.

I'd like to suggest we change those checkboxes for bigger ones - so it wont look like bullets. Or to replace for something entirely different, like "iPhone switches" (http://abpetkov.github.io/switchery/)

**Comment by felipefarias** [comment]
Hi @frenetic! 

You are right, the checkboxes are too small. It looks like bullets. I'm gonna make a PR with this improve. 

Thanks!
