### ISSUE TITLE
Use of the progress to show how much project is reusable

### ISSUE THREAD

**Issue by Marlysson** [vintasoftware/django-apps-checklist#9]
Could be use the a progress bar that when checked the list item increase the width of them , so would view "how much" the project it is reusable.

Example : Checklists on Trello.

**Comment by felipefarias** [comment]
Hey, I loved this idea!

For sure it will be an enhancement.

**Comment by felipefarias** [comment]
This issue was moved to the template of[ Django Checklists.](https://github.com/vintasoftware/devchecklists-template/)
